name: Go CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download Dependencies
        run: go mod download

      - name: Check Go Format
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not formatted"
            gofmt -l .
            exit 1
          fi

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Unit Test
        run: go test ./... -v -coverprofile=coverage.out

      - name: Build Project
        run: go build ./cmd/server

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out